version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongodb:27017
      TZ: Europe/Minsk
    ports:
      - '3000:3000'
      - '9229:9229'
    restart: always
    container_name: nestjs-expenses-app-dev

  mongodb:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
