name: Deploy to Cloud Run

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker Image Tag to Deploy'
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Deploy to Cloud Run (using WIF)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set Project Id
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE_NAME }} \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.event.inputs.tag }} \
            --platform managed \
            --region ${{ secrets.CLOUD_RUN_REGION }} \
            --allow-unauthenticated \
            --set-env-vars MONGODB_URI=${{ secrets.MONGODB_URI }},JWT_SECRET=${{ secrets.JWT_SECRET }}
