name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Call Common Steps
        uses: ./.github/workflows/common/install-environment-steps.yml

      - name: Run Linter
        run: yarn lint
